# Generated by Django 3.2.18 on 2024-02-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_image_post_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image5',
            new_name='image0',
        ),
    ]
