# Generated by Django 3.2.18 on 2024-02-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20240212_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='postIm',
        ),
    ]
