# Generated by Django 3.2.18 on 2024-02-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_product_image_postim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='postIm',
            new_name='postID',
        ),
    ]
